### ISSUE TITLE
doesn't support pug filters

### ISSUE THREAD

**Issue by wryk** [Ty3uK/parcel-plugin-pug#2]
I just tried parcel (with parcel-plugin-pug) on a little project and got this error : `A child of Block is of type Filter, which is not supported by pug-code-gen. Please use pug-filters to preprocess this AST.`

I uploaded a reproductible example at https://gist.github.com/wryk/db99b4f02d15ddf81d265fb7fb57222c

**Comment by Ty3uK** [comment]
Thanks, I'll fix it!

**Comment by Ty3uK** [comment]
Fixed in https://github.com/Ty3uK/parcel-plugin-pug/commit/08038b607cc022bf468988e04f8e5bc3a53e8090
Released version 0.2.2
Thanks for reporting!
