### ISSUE TITLE
how to using ?

### ISSUE THREAD

**Issue by jt3k** [Ty3uK/parcel-plugin-pug#21]
here are my commands in the console
```
npm init -y
npm i -D parcel-bundler parcel-plugin-pug

```
![](https://i.imgur.com/uIvQgjl.png)

maybe ну его нахер этот ооп-стиль бандлера ? одни ошибки с ним

**Comment by Ty3uK** [comment]
@jt3k 
<img width="953" alt="2018-06-26 9 43 36" src="https://user-images.githubusercontent.com/2384454/41893766-84b58116-7925-11e8-813d-6f3f6d8afb9b.png">

**Comment by jt3k** [comment]
😚
