### ISSUE TITLE
`srcset` in img support?

### ISSUE THREAD

**Issue by itslooklike** [Ty3uK/parcel-plugin-pug#9]
# Hello!

I try to use `srcset` in img tag, but plugin not resolve urls.
In pure html, parcel resolve this ursl, but in pug - not.

## Pure HTML:
```html
<img src='./assets/restaurants/restaurant-mcdonalds.png', srcset='./assets/restaurants/restaurant-mcdonalds@2x.png 2x'>
```
![image](https://user-images.githubusercontent.com/17547664/36555292-8f265d2e-1812-11e8-916d-1d8a33fe9b3f.png)

## Pug
```pug
img(src='./assets/restaurants/restaurant-mcdonalds.png', srcset='./assets/restaurants/restaurant-mcdonalds@2x.png 2x')
img(src='./assets/restaurants/restaurant-mcdonalds.png')&attributes({'srcset': './assets/restaurants/restaurant-mcdonalds@2x.png 2x'})
```
![image](https://user-images.githubusercontent.com/17547664/36555231-69768bb2-1812-11e8-8a25-e11af4f74e34.png)

i use:
```
    "parcel-bundler": "1.6.2",
    "parcel-plugin-pug": "0.2.5",
```
node v9.5.0

**Comment by Ty3uK** [comment]
Thanks, I’ll add this ASAP 🤝

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ty3uK** [comment]
Fixed in PR, thanks @dolma!
